### PR TITLE
Add interview recordings to research folder

### PR DESCRIPTION
**Pull request by Brightiya**
---
name: 🚀 Pull Request
about: Submit a pull request with changes or improvements
title: "[PR]: "
labels: []
assignees: ''
---

### 📄 **Pull Request Description**

---

### 📝 **Major Changes**

- Added reverse compatibility to X
- Fixed a rare occurrence of UI lag
- Improved error handling for Y

---

### ✅ **Type of Modifications**

- 🍃 New Feature  
- ♻️ Refactor  
- 🐛 Bug Fix  
- 🎨 Design/UX  
- 🔥 Optimization  
- 🧪 Tests  
- 📚 Documentation  
- 🎒 Other (please specify):  

---

### 🔗 **Related Issues**

- Fixes #
- Related to #

---

### 📊 **Testing Steps**

1. 
2. 
3. 

---

### 🛑 **Checklist Before Merging**
- [ ] Code follows the project's coding standards.
- [ ] Appropriate tests have been added or updated.
- [ ] Documentation updated where necessary.
- [ ] PR title and description are clear and concise.
- [ ] All checks pass (CI/CD, linting).

---

### 💬 **Additional Context**

User interviews were conducted and their responses recorded.

### CODE REVIEW

**Comment by ManahilMuhammad** [comment]
In user3.mp4, the audio is a bit difficult to understand. The volume of your (Bright's) voice is slightly low and the user's answers seem difficult to interpret due to audio quality.

**Comment by Brightiya** [comment]
@ManahilMuhammad Thank you for your observation.  User3 interview was conducted remotely. However, I could  hear myself and the user clearly and audibly from  the recording. So, what should we do with user3 recording?

**Comment by ManahilMuhammad** [comment]
@Brightiya I was thinking we could either _transcribe_ the recordings or provide a _summary_ for each one to make things clear.

**Comment by Brightiya** [comment]
@ManahilMuhammad  Yes, the recordings are going to be pinpointed  when we write user stories. 
Thanks.

**Comment by Maximus7474** [comment]
Good for merging I'd say ?

**Pull request merged**
